services:
  magicmirror:
    container_name: magicmirror-dev
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.js:/opt/magic_mirror/config/config.js
      - ./custom.css:/opt/magic_mirror/css/custom.css
      - ./modules:/opt/magic_mirror/modules
      - ./modules:/opt/magic_mirror/workspace/modules
      - ./config.js:/opt/magic_mirror/workspace/config.js
      - ./custom.css:/opt/magic_mirror/workspace/custom.css
    networks:
      - magicmirror_net

networks:
  magicmirror_net:
    driver: bridge

